import type { CollectionConfig } from 'payload'

export const Media: CollectionConfig = {
  slug: 'media',
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'alt',
      type: 'text',
      required: true,
      admin: {
        description: 'Alternative text for accessibility and SEO',
      },
    },
    {
      name: 'width',
      type: 'number',
      admin: {
        hidden: true,
        readOnly: true,
        description: 'Image width in pixels (auto-populated)',
      },
    },
    {
      name: 'height',
      type: 'number',
      admin: {
        hidden: true,
        readOnly: true,
        description: 'Image height in pixels (auto-populated)',
      },
    },
    {
      name: 'borderedVersion',
      type: 'group',
      admin: {
        description: 'Film border composite version (generated by processing script)',
      },
      fields: [
        {
          name: 'url',
          type: 'text',
          admin: {
            readOnly: true,
            description: 'URL of the bordered version in R2',
          },
        },
        {
          name: 'width',
          type: 'number',
          admin: {
            readOnly: true,
            description: 'Width of bordered version',
          },
        },
        {
          name: 'height',
          type: 'number',
          admin: {
            readOnly: true,
            description: 'Height of bordered version',
          },
        },
        {
          name: 'borderNumber',
          type: 'number',
          admin: {
            readOnly: true,
            description: 'Which film border was applied (1-8)',
          },
        },
      ],
    },
  ],
  upload: {
    // These are not supported on Workers yet due to lack of sharp
    crop: false,
    focalPoint: false,
    // TODO Phase 5: Add upload hooks to extract image dimensions
    // This prevents layout shift by allowing us to set aspect ratios
  },
}
