/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    gallery: Gallery;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility and SEO
   */
  alt: string;
  /**
   * Film border composite version (generated by processing script)
   */
  borderedVersion?: {
    /**
     * URL of the bordered version in R2
     */
    url?: string | null;
    /**
     * Width of bordered version
     */
    width?: number | null;
    /**
     * Height of bordered version
     */
    height?: number | null;
    /**
     * Which film border was applied (1-8)
     */
    borderNumber?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  /**
   * Image width in pixels (auto-populated)
   */
  width?: number | null;
  /**
   * Image height in pixels (auto-populated)
   */
  height?: number | null;
}
/**
 * Manage your portfolio gallery with photos, featured images, and text content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  /**
   * Internal title for this gallery (not displayed on website)
   */
  title: string;
  /**
   * Uncheck to hide this gallery from the website
   */
  published?: boolean | null;
  /**
   * Build your gallery by adding photos, featured photos, and text cards. Drag blocks to reorder. Featured photos and text cards display full-width.
   */
  items?:
    | (
        | {
            /**
             * Upload a photo for the masonry gallery
             */
            image: number | Media;
            /**
             * Optional caption displayed below the photo
             */
            caption?: string | null;
            /**
             * Mark this as a film photograph to display vintage camera icon and film details
             */
            isFilmPhoto?: boolean | null;
            /**
             * Film format used for this photograph
             */
            filmType?: ('35mm' | '645' | '6x6' | '6x7' | '6x9' | '4x5' | '8x10') | null;
            /**
             * Film stock used (e.g., "Kodak Gold 200", "Portra 400", "HP5 Plus")
             */
            filmStock?: string | null;
            /**
             * Render this photo in black and white (grayscale filter)
             */
            blackAndWhite?: boolean | null;
            /**
             * Apply a film border overlay to this photo (requires running border processing script)
             */
            applyFilmBorder?: boolean | null;
            /**
             * Select which film border design to apply (1-8)
             */
            filmBorderNumber?: (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'photo';
          }
        | {
            /**
             * Upload multiple photos at once - they will all be added to the masonry gallery
             */
            images: (number | Media)[];
            /**
             * Mark all photos in this batch as film photographs
             */
            isFilmPhoto?: boolean | null;
            /**
             * Film format used for all photos in this batch
             */
            filmType?: ('35mm' | '645' | '6x6' | '6x7' | '6x9' | '4x5' | '8x10') | null;
            /**
             * Film stock used (e.g., "Kodak Gold 200", "Portra 400", "HP5 Plus")
             */
            filmStock?: string | null;
            /**
             * Render all photos in this batch in black and white (grayscale filter)
             */
            blackAndWhite?: boolean | null;
            /**
             * Apply a film border overlay to all photos in this batch (requires running border processing script)
             */
            applyFilmBorder?: boolean | null;
            /**
             * Select which film border design to apply to all photos (1-8)
             */
            filmBorderNumber?: (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'photoBulk';
          }
        | {
            /**
             * Upload multiple photos - displays in 3-column grid (full-width section)
             */
            images: (number | Media)[];
            /**
             * Mark all photos in this batch as film photographs
             */
            isFilmPhoto?: boolean | null;
            /**
             * Film format used for all photos in this batch
             */
            filmType?: ('35mm' | '645' | '6x6' | '6x7' | '6x9' | '4x5' | '8x10') | null;
            /**
             * Film stock used (e.g., "Kodak Gold 200", "Portra 400", "HP5 Plus")
             */
            filmStock?: string | null;
            /**
             * Render all photos in this batch in black and white (grayscale filter)
             */
            blackAndWhite?: boolean | null;
            /**
             * Apply a film border overlay to all photos in this batch (requires running border processing script)
             */
            applyFilmBorder?: boolean | null;
            /**
             * Select which film border design to apply to all photos (1-8)
             */
            filmBorderNumber?: (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'photoBulk3Across';
          }
        | {
            /**
             * Featured photo - displays full-width across the page
             */
            image: number | Media;
            /**
             * Show overlay with text and/or buttons
             */
            enableOverlay?: boolean | null;
            /**
             * Add text blocks and buttons. Each can be positioned independently.
             */
            overlayContent?:
              | (
                  | {
                      /**
                       * Text content (headline, tagline, paragraph, etc.)
                       */
                      text?: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      } | null;
                      /**
                       * Horizontal alignment
                       */
                      alignment?: ('left' | 'center' | 'right') | null;
                      /**
                       * Vertical position
                       */
                      verticalPosition?: ('top' | 'top-third' | 'center' | 'bottom-third' | 'bottom') | null;
                      /**
                       * Maximum width
                       */
                      width?: ('small' | 'medium' | 'large' | 'full') | null;
                      /**
                       * Font size in pixels (24-120)
                       */
                      fontSize?: number | null;
                      /**
                       * Font color as hex code (e.g., #ffffff for white)
                       */
                      fontColor?: string | null;
                      /**
                       * Line spacing (use "Relaxed" or "Loose" for large fonts)
                       */
                      lineHeight?: ('tight' | 'normal' | 'relaxed' | 'loose') | null;
                      /**
                       * Font family
                       */
                      fontFamily?: ('lobster-two' | 'playfair' | 'bebas' | 'inter') | null;
                      /**
                       * Add shadow for better readability
                       */
                      textShadow?: boolean | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'overlayText';
                    }
                  | {
                      /**
                       * Button text (e.g., "Contact Me", "Get Started")
                       */
                      buttonText: string;
                      /**
                       * URL (e.g., "/contact", "mailto:email@example.com")
                       */
                      buttonLink: string;
                      /**
                       * Horizontal alignment
                       */
                      alignment?: ('left' | 'center' | 'right') | null;
                      /**
                       * Vertical position
                       */
                      verticalPosition?: ('top' | 'top-third' | 'center' | 'bottom-third' | 'bottom') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'overlayButton';
                    }
                )[]
              | null;
            /**
             * Darkness of the background overlay for text readability
             */
            overlayIntensity?: ('none' | 'light' | 'medium' | 'heavy') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredPhoto';
          }
        | {
            /**
             * Text content for storytelling or context. Displays full-width. Keep to 2-4 paragraphs for optimal layout.
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Background color scheme for the text card
             */
            backgroundColor?: ('light' | 'dark' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textCard';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  borderedVersion?:
    | T
    | {
        url?: T;
        width?: T;
        height?: T;
        borderNumber?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  published?: T;
  items?:
    | T
    | {
        photo?:
          | T
          | {
              image?: T;
              caption?: T;
              isFilmPhoto?: T;
              filmType?: T;
              filmStock?: T;
              blackAndWhite?: T;
              applyFilmBorder?: T;
              filmBorderNumber?: T;
              id?: T;
              blockName?: T;
            };
        photoBulk?:
          | T
          | {
              images?: T;
              isFilmPhoto?: T;
              filmType?: T;
              filmStock?: T;
              blackAndWhite?: T;
              applyFilmBorder?: T;
              filmBorderNumber?: T;
              id?: T;
              blockName?: T;
            };
        photoBulk3Across?:
          | T
          | {
              images?: T;
              isFilmPhoto?: T;
              filmType?: T;
              filmStock?: T;
              blackAndWhite?: T;
              applyFilmBorder?: T;
              filmBorderNumber?: T;
              id?: T;
              blockName?: T;
            };
        featuredPhoto?:
          | T
          | {
              image?: T;
              enableOverlay?: T;
              overlayContent?:
                | T
                | {
                    overlayText?:
                      | T
                      | {
                          text?: T;
                          alignment?: T;
                          verticalPosition?: T;
                          width?: T;
                          fontSize?: T;
                          fontColor?: T;
                          lineHeight?: T;
                          fontFamily?: T;
                          textShadow?: T;
                          id?: T;
                          blockName?: T;
                        };
                    overlayButton?:
                      | T
                      | {
                          buttonText?: T;
                          buttonLink?: T;
                          alignment?: T;
                          verticalPosition?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              overlayIntensity?: T;
              id?: T;
              blockName?: T;
            };
        textCard?:
          | T
          | {
              content?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}